### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by Dreadox** [leandrovieiraa/ytubebot#12]
←[1;32;40m [ OK ] ←[0m: ←[1;33;40m2022-07-02:16:32:13 ←[0m - Initializing system.
←[1;32;40m [ OK ] ←[0m: ←[1;33;40m2022-07-02:16:32:13 ←[0m - Initializing watcher with async instances count: 1
←[1;32;40m [ OK ] ←[0m: ←[1;33;40m2022-07-02:16:32:13 ←[0m - Playlist data loaded successfully.
←[1;32;40m [ OK ] ←[0m: ←[1;33;40m2022-07-02:16:32:13 ←[0m - Initializing controllers
Task exception was never retrieved
future: <Task finished coro=<Controller.start_controller() done, defined at D:\Hacking\ytubebot\controller.py:7> exception=WebDriverException('unknown error: cannot find Chrome binary\n  (Driver info: chromedriver=73.0.3683.20 (8e2b610813e167eee3619ac4ce6e42e3ec622017),platform=Windows NT 10.0.19044 x86_64)', None, None)>
Traceback (most recent call last):
  File "D:\Hacking\ytubebot\controller.py", line 21, in start_controller
    driver = webdriver.Chrome(chrome_options=options, executable_path=r'./driver/chromedriver.exe')
  File "C:\Users\Dreadox\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\Dreadox\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Dreadox\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Dreadox\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Dreadox\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=73.0.3683.20 (8e2b610813e167eee3619ac4ce6e42e3ec622017),platform=Windows NT 10.0.19044 x86_64)

←[1;36;40m
 =========== Finish =========== ←[0m

**Comment by Dreadox** [comment]
Everything is fine here

D:\Hacking\ytubebot>pip install -r requirements.txt
Requirement already satisfied: astroid==2.2.0 in c:\users\dreadox\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: colorama==0.4.1 in c:\users\dreadox\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: isort==4.3.9 in c:\users\dreadox\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 3)) (4.3.9)
Requirement already satisfied: lazy-object-proxy==1.3.1 in c:\users\dreadox\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 4)) (1.3.1)
Requirement already satisfied: mccabe==0.6.1 in c:\users\dreadox\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 5)) (0.6.1)
Requirement already satisfied: numpy==1.16.2 in c:\users\dreadox\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 6)) (1.16.2)
Requirement already satisfied: pylint==2.3.0 in c:\users\dreadox\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 7)) (2.3.0)
Requirement already satisfied: selenium==3.141.0 in c:\users\dreadox\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 8)) (3.141.0)
Requirement already satisfied: six==1.12.0 in c:\users\dreadox\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 9)) (1.12.0)
Requirement already satisfied: typed-ast==1.3.1 in c:\users\dreadox\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 10)) (1.3.1)
Requirement already satisfied: urllib3==1.24.1 in c:\users\dreadox\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 11)) (1.24.1)
Requirement already satisfied: wrapt==1.11.1 in c:\users\dreadox\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 12)) (1.11.1)

**Comment by javi22020** [comment]
Add wheel==0.38.4 to requirements.txt, in the line before typed-ast
